from datetime import datetime

import pytest
import responses

from bnmpy import BASE_URL, Bnmpy

null = None


class TestInterbankSwap:
    def test_latest(self, mock_interbank_swap):
        fto = Bnmpy().interbank_swap()
        assert fto.endpoints == ["interbank-swap"]
        assert len(fto.data) == 1
        assert all(
            [
                k in fto.data[0]
                for k in [
                    "date",
                    "overnight",
                    "1_week",
                    "2_week",
                    "1_month",
                    "2_month",
                    "3_month",
                    "6_month",
                    "9_month",
                    "12_month",
                    "more_1_year",
                ]
            ]
        )

    def test_date_single(self, mock_interbank_swap):
        fto = Bnmpy().interbank_swap(date=datetime(2019, 1, 2))
        assert fto.endpoints == ["interbank-swap/date/2019-01-02"]
        assert len(fto.data) == 1

    def test_date_multi(self, mock_interbank_swap):
        fto = Bnmpy().interbank_swap(date=[datetime(2019, 1, 2), datetime(2019, 1, 3)])
        assert fto.endpoints == [
            "interbank-swap/date/2019-01-02",
            "interbank-swap/date/2019-01-03",
        ]
        assert len(fto.data) == 2

    def test_range_within_month(self, mock_interbank_swap):
        fto = Bnmpy().interbank_swap(
            start=datetime(2019, 1, 2), end=datetime(2019, 1, 4)
        )
        assert fto.endpoints == ["interbank-swap/year/2019/month/01"]
        assert len(fto.data) == 3

    def test_range_across_months(self, mock_interbank_swap):
        fto = Bnmpy().interbank_swap(
            start=datetime(2019, 1, 29), end=datetime(2019, 2, 4)
        )
        assert fto.endpoints == [
            "interbank-swap/year/2019/month/01",
            "interbank-swap/year/2019/month/02",
        ]
        assert len(fto.data) == 4


@pytest.fixture
def mock_interbank_swap():
    with responses.RequestsMock(assert_all_requests_are_fired=False) as r:
        r.add(
            responses.GET,
            BASE_URL + "interbank-swap",
            json={
                "data": {
                    "date": "2019-11-06",
                    "overnight": 3195.56,
                    "1_week": 27,
                    "2_week": 150.14,
                    "1_month": 49.96,
                    "2_month": 96.83,
                    "3_month": 33.32,
                    "6_month": 45,
                    "9_month": 15,
                    "12_month": null,
                    "more_1_year": null,
                },
                "meta": {"last_updated": "2019-11-06 07:00:04", "total_result": 1},
            },
            status=200,
        )
        r.add(
            responses.GET,
            BASE_URL + "interbank-swap/date/2019-01-02",
            json={
                "data": {
                    "date": "2019-01-02",
                    "overnight": 4333.7,
                    "1_week": 290.01,
                    "2_week": 0.01,
                    "1_month": 0.31,
                    "2_month": 50.03,
                    "3_month": 277.81,
                    "6_month": null,
                    "9_month": 40,
                    "12_month": null,
                    "more_1_year": 20,
                },
                "meta": {"last_updated": "2019-11-06 07:00:04", "total_result": 1},
            },
            status=200,
        )
        r.add(
            responses.GET,
            BASE_URL + "interbank-swap/date/2019-01-03",
            json={
                "data": {
                    "date": "2019-01-03",
                    "overnight": 3230.22,
                    "1_week": 147,
                    "2_week": 185.06,
                    "1_month": 60.81,
                    "2_month": 129.05,
                    "3_month": 444.02,
                    "6_month": 170,
                    "9_month": 104,
                    "12_month": 25,
                    "more_1_year": 25,
                },
                "meta": {"last_updated": "2019-11-06 07:00:04", "total_result": 1},
            },
            status=200,
        )
        r.add(
            responses.GET,
            BASE_URL + "interbank-swap/date/2019-01-04",
            json={
                "data": {
                    "date": "2019-01-04",
                    "overnight": 2834.76,
                    "1_week": 203.5,
                    "2_week": null,
                    "1_month": 79.38,
                    "2_month": 150.25,
                    "3_month": 367.5,
                    "6_month": 50,
                    "9_month": null,
                    "12_month": 10,
                    "more_1_year": 50,
                },
                "meta": {"last_updated": "2019-11-06 07:00:04", "total_result": 1},
            },
            status=200,
        )
        r.add(
            responses.GET,
            BASE_URL + "interbank-swap/year/2019/month/01",
            json={
                "data": [
                    {
                        "date": "2019-01-02",
                        "overnight": 4333.7,
                        "1_week": 290.01,
                        "2_week": 0.01,
                        "1_month": 0.31,
                        "2_month": 50.03,
                        "3_month": 277.81,
                        "6_month": null,
                        "9_month": 40,
                        "12_month": null,
                        "more_1_year": 20,
                    },
                    {
                        "date": "2019-01-03",
                        "overnight": 3230.22,
                        "1_week": 147,
                        "2_week": 185.06,
                        "1_month": 60.81,
                        "2_month": 129.05,
                        "3_month": 444.02,
                        "6_month": 170,
                        "9_month": 104,
                        "12_month": 25,
                        "more_1_year": 25,
                    },
                    {
                        "date": "2019-01-04",
                        "overnight": 2834.76,
                        "1_week": 203.5,
                        "2_week": null,
                        "1_month": 79.38,
                        "2_month": 150.25,
                        "3_month": 367.5,
                        "6_month": 50,
                        "9_month": null,
                        "12_month": 10,
                        "more_1_year": 50,
                    },
                    {
                        "date": "2019-01-07",
                        "overnight": 3554.13,
                        "1_week": 207.52,
                        "2_week": 6.19,
                        "1_month": 120.05,
                        "2_month": 100.29,
                        "3_month": 212.39,
                        "6_month": 80,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-01-08",
                        "overnight": 2749.51,
                        "1_week": null,
                        "2_week": 0.09,
                        "1_month": 85.28,
                        "2_month": 95.24,
                        "3_month": 50.32,
                        "6_month": 4.86,
                        "9_month": null,
                        "12_month": 35,
                        "more_1_year": 15.3,
                    },
                    {
                        "date": "2019-01-09",
                        "overnight": 3827.86,
                        "1_week": 340,
                        "2_week": 50.85,
                        "1_month": 10.04,
                        "2_month": 100.14,
                        "3_month": 102.5,
                        "6_month": 157.5,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-01-10",
                        "overnight": 2630.92,
                        "1_week": 27.22,
                        "2_week": 50.9,
                        "1_month": 25.81,
                        "2_month": 51.12,
                        "3_month": 220.46,
                        "6_month": 277.7,
                        "9_month": null,
                        "12_month": 35,
                        "more_1_year": 5,
                    },
                    {
                        "date": "2019-01-11",
                        "overnight": 2701.38,
                        "1_week": 224.3,
                        "2_week": 0.08,
                        "1_month": 3.86,
                        "2_month": 5.24,
                        "3_month": 110.83,
                        "6_month": 100,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-01-14",
                        "overnight": 3340.44,
                        "1_week": 50.5,
                        "2_week": 120.17,
                        "1_month": 0.05,
                        "2_month": 0.09,
                        "3_month": 81.8,
                        "6_month": 31.24,
                        "9_month": null,
                        "12_month": 17.07,
                        "more_1_year": 50.4,
                    },
                    {
                        "date": "2019-01-15",
                        "overnight": 2597.58,
                        "1_week": 116,
                        "2_week": 160.96,
                        "1_month": 300.31,
                        "2_month": 20.07,
                        "3_month": 300.07,
                        "6_month": 100,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": 10,
                    },
                    {
                        "date": "2019-01-16",
                        "overnight": 2665.29,
                        "1_week": 100,
                        "2_week": 0.9,
                        "1_month": 0.2,
                        "2_month": 170.01,
                        "3_month": 212.21,
                        "6_month": 120.2,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": 35,
                    },
                    {
                        "date": "2019-01-17",
                        "overnight": 3486.54,
                        "1_week": 251.01,
                        "2_week": 54.94,
                        "1_month": 164.48,
                        "2_month": 20.09,
                        "3_month": 227.38,
                        "6_month": 112,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-01-18",
                        "overnight": 2942.93,
                        "1_week": 145,
                        "2_week": 26.12,
                        "1_month": 121.47,
                        "2_month": 5,
                        "3_month": 65.21,
                        "6_month": 0.67,
                        "9_month": null,
                        "12_month": 30,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-01-22",
                        "overnight": 3631.53,
                        "1_week": 5.08,
                        "2_week": null,
                        "1_month": 326.4,
                        "2_month": 4.08,
                        "3_month": 50.88,
                        "6_month": null,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-01-23",
                        "overnight": 2296.98,
                        "1_week": 232.56,
                        "2_week": 120.55,
                        "1_month": 493.04,
                        "2_month": 165,
                        "3_month": 84.3,
                        "6_month": 1.48,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-01-24",
                        "overnight": 2699.08,
                        "1_week": 165.23,
                        "2_week": 330,
                        "1_month": 321.06,
                        "2_month": 14.62,
                        "3_month": 151.05,
                        "6_month": 61,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": 6,
                    },
                    {
                        "date": "2019-01-25",
                        "overnight": 2073.97,
                        "1_week": 200.18,
                        "2_week": 268.04,
                        "1_month": 71.62,
                        "2_month": 263.67,
                        "3_month": 463.2,
                        "6_month": 150,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": 30,
                    },
                    {
                        "date": "2019-01-28",
                        "overnight": 1511.37,
                        "1_week": 1.53,
                        "2_week": 310.5,
                        "1_month": 0.59,
                        "2_month": 0.03,
                        "3_month": 20.6,
                        "6_month": 70,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-01-29",
                        "overnight": 2027.46,
                        "1_week": 0.1,
                        "2_week": 155.02,
                        "1_month": 159.4,
                        "2_month": 4.77,
                        "3_month": 282.42,
                        "6_month": 125,
                        "9_month": null,
                        "12_month": 10,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-01-30",
                        "overnight": 1728.21,
                        "1_week": 74.64,
                        "2_week": 95.53,
                        "1_month": 70.17,
                        "2_month": 180.07,
                        "3_month": 265.2,
                        "6_month": 45,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-01-31",
                        "overnight": 2028.57,
                        "1_week": 238.76,
                        "2_week": 1.37,
                        "1_month": 62.18,
                        "2_month": 286.78,
                        "3_month": 145.31,
                        "6_month": 40,
                        "9_month": null,
                        "12_month": 37,
                        "more_1_year": 0.8,
                    },
                ],
                "meta": {"last_updated": "2019-11-06 07:00:04", "total_result": 21},
            },
            status=200,
        )
        r.add(
            responses.GET,
            BASE_URL + "interbank-swap/year/2019/month/02",
            json={
                "data": [
                    {
                        "date": "2019-02-04",
                        "overnight": 1338.42,
                        "1_week": 50,
                        "2_week": 0.43,
                        "1_month": 2.84,
                        "2_month": 60,
                        "3_month": 60,
                        "6_month": null,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": 0.58,
                    },
                    {
                        "date": "2019-02-07",
                        "overnight": 1672.28,
                        "1_week": 5.5,
                        "2_week": 26.17,
                        "1_month": 160,
                        "2_month": 201.48,
                        "3_month": 66.74,
                        "6_month": 55.1,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-02-08",
                        "overnight": 1522.43,
                        "1_week": 80.52,
                        "2_week": 280.03,
                        "1_month": null,
                        "2_month": 120.04,
                        "3_month": 206.08,
                        "6_month": 112.5,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-02-11",
                        "overnight": 1588.47,
                        "1_week": 305.24,
                        "2_week": 71.2,
                        "1_month": 199.27,
                        "2_month": 115.19,
                        "3_month": 350.35,
                        "6_month": 0.5,
                        "9_month": null,
                        "12_month": 20,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-02-12",
                        "overnight": 1869.33,
                        "1_week": 400,
                        "2_week": 280.54,
                        "1_month": 127.82,
                        "2_month": 209,
                        "3_month": 303.03,
                        "6_month": 3,
                        "9_month": null,
                        "12_month": 333,
                        "more_1_year": 2.45,
                    },
                    {
                        "date": "2019-02-13",
                        "overnight": 1804.08,
                        "1_week": 6.02,
                        "2_week": 476.35,
                        "1_month": 55.36,
                        "2_month": 448.06,
                        "3_month": 310.43,
                        "6_month": 170.5,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-02-14",
                        "overnight": 1635.73,
                        "1_week": 24.38,
                        "2_week": 100.39,
                        "1_month": 1.47,
                        "2_month": 0.02,
                        "3_month": 330,
                        "6_month": 70,
                        "9_month": 50,
                        "12_month": null,
                        "more_1_year": 1.1,
                    },
                    {
                        "date": "2019-02-15",
                        "overnight": 1937.8,
                        "1_week": 3,
                        "2_week": 0.33,
                        "1_month": 50.01,
                        "2_month": 42.99,
                        "3_month": 0.71,
                        "6_month": 1.5,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": 18,
                    },
                    {
                        "date": "2019-02-18",
                        "overnight": 333.28,
                        "1_week": 2,
                        "2_week": 0.06,
                        "1_month": 31,
                        "2_month": 0.63,
                        "3_month": 0.06,
                        "6_month": 71.7,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-02-19",
                        "overnight": 2136.27,
                        "1_week": 144.1,
                        "2_week": 0.1,
                        "1_month": 281.11,
                        "2_month": 1.79,
                        "3_month": 221.14,
                        "6_month": 163.71,
                        "9_month": 250,
                        "12_month": 125,
                        "more_1_year": 21,
                    },
                    {
                        "date": "2019-02-20",
                        "overnight": 2198.97,
                        "1_week": 267.64,
                        "2_week": 0.69,
                        "1_month": 205.01,
                        "2_month": 2.22,
                        "3_month": 155.02,
                        "6_month": 50,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": 65,
                    },
                    {
                        "date": "2019-02-21",
                        "overnight": 2181.49,
                        "1_week": 70.04,
                        "2_week": 5.01,
                        "1_month": null,
                        "2_month": null,
                        "3_month": 150.1,
                        "6_month": 190,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-02-22",
                        "overnight": 1982.46,
                        "1_week": 224.45,
                        "2_week": 0.11,
                        "1_month": 104.2,
                        "2_month": 70.22,
                        "3_month": 251.53,
                        "6_month": 63.05,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": 35.99,
                    },
                    {
                        "date": "2019-02-25",
                        "overnight": 2010.47,
                        "1_week": 5.01,
                        "2_week": 30.04,
                        "1_month": 95.02,
                        "2_month": 50.85,
                        "3_month": 0.12,
                        "6_month": 85.83,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                    {
                        "date": "2019-02-26",
                        "overnight": 2724.03,
                        "1_week": 630,
                        "2_week": 9.59,
                        "1_month": 10.04,
                        "2_month": 72.49,
                        "3_month": 121.48,
                        "6_month": 120.2,
                        "9_month": null,
                        "12_month": 90,
                        "more_1_year": 22.46,
                    },
                    {
                        "date": "2019-02-27",
                        "overnight": 1931.99,
                        "1_week": 115,
                        "2_week": 4.13,
                        "1_month": 175.15,
                        "2_month": 21.17,
                        "3_month": 100.51,
                        "6_month": 45,
                        "9_month": 0.69,
                        "12_month": null,
                        "more_1_year": 60,
                    },
                    {
                        "date": "2019-02-28",
                        "overnight": 2161.18,
                        "1_week": 235,
                        "2_week": 23.14,
                        "1_month": 108.62,
                        "2_month": 2.77,
                        "3_month": 190.11,
                        "6_month": 100,
                        "9_month": null,
                        "12_month": null,
                        "more_1_year": null,
                    },
                ],
                "meta": {"last_updated": "2019-11-06 07:00:04", "total_result": 17},
            },
            status=200,
        )
        yield r
